/*
 * This source file was generated by the Gradle 'init' task
 */
package tdoc1;

import javafx.application.Application;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.stage.Stage;

public class App extends Application{
    
    public void start (Stage stage) throws Exception{
        
        FXMLLoader loader = new FXMLLoader(getClass().getResource("/tdoc1/AuthScene.fxml"));

        Parent root = loader.load();

        Scene scene = new Scene(root);

        stage.setScene(scene);
        stage.setTitle("JavaFX Application");

        stage.show();
    }
    public static void main(String[] args) {
        launch (args);
    }
}
